apiVersion: v1
kind: Secret
metadata:
  name: ptc-credentials
  namespace: default
type: Opaque
stringData:
  ptcHostname: "http://10.220.112.90:42099"
  ptcUsername: "admin"
  ptcPassword: "admin"
  ptcTenantId: "tnt-a218fe93"
  ptcClientId: "ptc-cli"

