apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: PTCMachine
metadata:
  name: ptc-control-plane-node-1
  namespace: default
spec:
  instanceType: medium
  bootDiskSize: 50
  image: "ubuntu-22.04"
  network:
    name: "vlan-2415"
    ipFromPoolRef:
      apiVersion: ipam.cluster.x-k8s.io/v1alpha1
      kind: InClusterIPPool
      name: ptc-ip-pool
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: PTCMachine
metadata:
  name: ptc-worker-node-1
  namespace: default
spec:
  instanceType: large
  bootDiskSize: 50
  image: "ubuntu-22.04"
  network:
    name: "vlan-2415"
    ipFromPoolRef:
      apiVersion: ipam.cluster.x-k8s.io/v1alpha1
      kind: InClusterIPPool
      name: ptc-ip-pool
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: PTCMachine
metadata:
  name: ptc-worker-node-2
  namespace: default
spec:
  instanceType: large
  bootDiskSize: 50
  image: "ubuntu-22.04"
  network:
    name: "vlan-2415"
    ipFromPoolRef:
      apiVersion: ipam.cluster.x-k8s.io/v1alpha1
      kind: InClusterIPPool
      name: ptc-ip-pool
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: PTCMachine
metadata:
  name: ptc-worker-node-3
  namespace: default
spec:
  instanceType: large
  bootDiskSize: 50
  image: "ubuntu-22.04"
  network:
    name: "vlan-2415"
    ipFromPoolRef:
      apiVersion: ipam.cluster.x-k8s.io/v1alpha1
      kind: InClusterIPPool
      name: ptc-ip-pool
