# 1. Core CAPI Machine (This makes `kubectl get machines` work)
apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  name: ptc-worker-node1
  namespace: default
  labels:
    cluster.x-k8s.io/cluster-name: ptc-cluster-demo
    cluster.x-k8s.io/control-plane: ""
spec:
  clusterName: ptc-cluster-demo
  bootstrap:
    dataSecretName: ptc-dummy-bootstrap-data
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: PTCMachine
    name: ptc-worker-node-1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: PTCMachine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: ptc-cluster-demo
    cluster.x-k8s.io/control-plane: ""
  name: ptc-worker-node-1
  namespace: default
spec:
  sshKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAar+cWR6/1L1qOYQ+hxNA8zi7YSLSyApo1h+IBAPWZC"
  tags:
    - "cluster.version=0.0.1"
    - "ptc.client.version=0.5.8"
  instanceType: large
  bootDiskSize: 50
  image: "ubuntu-24.04"
  network:
    name: "dev-net"
    ipFromPoolRef:
      apiGroup: ipam.cluster.x-k8s.io
      kind: InClusterIPPool
      name: ptc-ip-pool
